# Generated by Django 6.0.7 on 2026-07-27 21:05

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dpi', models.CharField(blank=True, max_length=50, verbose_name='DPI/ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_reparacion', 'En Reparacion'), ('dado_de_baja', 'Dado de Baja')], default='disponible', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CambioReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reparacion', 'Reparacion'), ('cambio_pieza', 'Cambio de Pieza'), ('actualizacion', 'Actualizacion'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('descripcion', models.TextField()),
                ('tecnico', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Cambio/Reparacion',
                'verbose_name_plural': 'Cambios y Reparaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('accesorios_entregados', models.ManyToManyField(blank=True, to='inventario.accesorio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='HojaResponsabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to=inventario.models.path_firma)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to=inventario.models.path_pdf)),
                ('condiciones', models.TextField(default='El abajo firmante se hace responsable del equipo descrito en esta hoja. Se compromete a devolverlo en las mismas condiciones en que fue recibido. En caso de dano o perdida, cubrira el costo de reparacion o reposicion.')),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoja', to='inventario.asignacion')),
            ],
            options={
                'verbose_name': 'Hoja de Responsabilidad',
                'verbose_name_plural': 'Hojas de Responsabilidad',
            },
        ),
    ]
