# Generated by Django 4.2.30 on 2026-07-29 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_notificacion_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('encargado', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('limpieza', 'Limpieza general'), ('revision_software', 'Revision de software'), ('cambio_pasta', 'Cambio de pasta termica'), ('revision_bateria', 'Revision de bateria'), ('actualizacion_so', 'Actualizacion de sistema operativo')], max_length=30)),
                ('frecuencia_meses', models.PositiveIntegerField(default=6)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento Preventivo',
                'verbose_name_plural': 'Mantenimientos Preventivos',
                'ordering': ['proxima_fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMantenimientoPreventivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tipo', models.CharField(choices=[('limpieza', 'Limpieza general'), ('revision_software', 'Revision de software'), ('cambio_pasta', 'Cambio de pasta termica'), ('revision_bateria', 'Revision de bateria'), ('actualizacion_so', 'Actualizacion de sistema operativo')], max_length=30)),
                ('frecuencia_meses', models.PositiveIntegerField(default=6)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mantenimiento Preventivo',
                'verbose_name_plural': 'historical Mantenimientos Preventivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inventario.sucursal'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.sucursal'),
        ),
    ]
