# Generated by Django 4.2.30 on 2026-07-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_sucursal_mantenimientopreventivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientopreventivo',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='historicalequipo',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='HistoricalMantenimientoPreventivo',
        ),
        migrations.DeleteModel(
            name='MantenimientoPreventivo',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
