# Generated by Django 4.2.30 on 2026-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_mantenimientopreventivo_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='url_cloudinary',
            field=models.URLField(blank=True, null=True, verbose_name='URL en Cloudinary'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/%Y/%m/'),
        ),
    ]
