# Generated by Django 4.2.30 on 2026-08-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0007_evidencia_url_cloudinary_alter_evidencia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('garantia', 'Garantia por vencer'), ('stock', 'Stock bajo'), ('revision', 'Revision pendiente'), ('licencia', 'Licencia por vencer'), ('mantenimiento', 'Mantenimiento preventivo'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Entrega/Asignacion'), ('devolucion', 'Devolucion'), ('reparacion', 'Reparacion'), ('mantenimiento', 'Mantenimiento Preventivo'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='SoftwareLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tipo', models.CharField(choices=[('os', 'Sistema Operativo'), ('office', 'Microsoft Office'), ('antivirus', 'Antivirus'), ('cad', 'Software CAD/Diseño'), ('db', 'Base de Datos'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(blank=True, max_length=500, verbose_name='Clave/Licencia')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Licencia de Software',
                'verbose_name_plural': 'Licencias de Software',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('ultima_fecha', models.DateField(blank=True, null=True, verbose_name='Ultima realizacion')),
                ('proxima_fecha', models.DateField(blank=True, null=True, verbose_name='Proximo mantenimiento')),
                ('tecnico', models.CharField(blank=True, max_length=200)),
                ('completado', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_preventivos', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento Preventivo',
                'verbose_name_plural': 'Mantenimientos Preventivos',
                'ordering': ['proxima_fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSoftwareLicencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tipo', models.CharField(choices=[('os', 'Sistema Operativo'), ('office', 'Microsoft Office'), ('antivirus', 'Antivirus'), ('cad', 'Software CAD/Diseño'), ('db', 'Base de Datos'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(blank=True, max_length=500, verbose_name='Clave/Licencia')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Licencia de Software',
                'verbose_name_plural': 'historical Licencias de Software',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMantenimientoPreventivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('ultima_fecha', models.DateField(blank=True, null=True, verbose_name='Ultima realizacion')),
                ('proxima_fecha', models.DateField(blank=True, null=True, verbose_name='Proximo mantenimiento')),
                ('tecnico', models.CharField(blank=True, max_length=200)),
                ('completado', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mantenimiento Preventivo',
                'verbose_name_plural': 'historical Mantenimientos Preventivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='alerta',
            name='licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.softwarelicencia'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.mantenimientopreventivo'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='inventario.ubicacion', verbose_name='Ubicacion fisica'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='historicalasignacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.ubicacion', verbose_name='Ubicacion fisica'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.ubicacion'),
        ),
    ]
