# Generated by Django 4.2.30 on 2026-08-04 19:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_licencias_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
        migrations.AlterField(
            model_name='historicalequipo',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
